services:
  flask-app:
    build:
        context: .
        dockerfile: Dockerfile
    image: sunmh207/ai-codereview-gitlab:1.2.2
    ports:
      - "5001:5001"
      - "5002:5002"
    volumes:
      - ./.env:/app/.env
      - ./log:/app/log
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
