services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: ghcr.io/mashb1t/ai-codereview-gitlab:1
    ports:
      - "5001:5001"
      - "5002:5002"
    volumes:
      - ./biz:/app/biz
      - ./data:/app/data
      - ./locales:/app/locales
      - ./log:/app/log
      - ./api.py:/app/api.py
      - ./requirements.txt:/app/requirements.txt
      - ./ui.py:/app/ui.py
    env_file:
      - ./conf/.env
    depends_on:
      redis:
        condition: service_started
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: worker
    image: ghcr.io/mashb1t/ai-codereview-gitlab:1-worker
    volumes_from:
      - app
    env_file:
      - ./conf/.env
    depends_on:
      redis:
        condition: service_started
    restart: unless-stopped

  redis:
    image: redis:alpine
    env_file:
      - ./conf/.env
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data: