services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: mashb1t/ai-codereview-gitlab:1
    ports:
      - "5001:5001"
      - "5002:5002"
    volumes:
      - ./biz:/app/biz
      - ./core:/app/core
      - ./data:/app/data
      - ./log:/app/log
      - ./api.py:/app/api.py
      - ./prompt_templates.yml:/app/prompt_templates.yml
      - ./requirements.txt:/app/requirements.txt
      - ./ui.py:/app/ui.py
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_started
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: worker
    image: mashb1t/ai-codereview-gitlab:1-worker
    volumes_from:
      - app
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_started
    restart: unless-stopped

  redis:
    image: redis:alpine
#    ports:
#      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data: