services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    image: ghcr.io/mashb1t/ai-codereview-gitlab:1
    ports:
      - "5001:5001"
      - "5002:5002"
    volumes:
      - ./data:/app/data
      - ./locales:/app/locales
      - ./log:/app/log
    env_file:
      - ./conf/.env
    restart: unless-stopped